package finalproject;

import Controller.Connect;
import Model.BindTable;
import Model.Product2;
import Model.TheModel;
import Model.UpdateTable;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.TableModel;

/**
 *
 * @author Aditya Pribadi
 */
public class UserBrandInterface extends javax.swing.JFrame {

     public void populate() throws SQLException{
        BindTable mq = new BindTable();
        ArrayList<Product2> list = mq.BindTable();
        String[] columnName = {"Amount","PhoneName","Merek","Harga", "Picture"};
        Object[][] rows = new Object[list.size()][9];
        for(int i = 0; i < list.size(); i++){
             rows[i][0] = list.get(i).getAmount();
             rows[i][1] = list.get(i).getBrand();
             rows[i][2] = list.get(i).getMerek();
             rows[i][3] = list.get(i).getHarga();
             if(list.get(i).getImage() != null){
                
             ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getImage()).getImage()
             .getScaledInstance(80, 80, Image.SCALE_SMOOTH) );   
                
            rows[i][4] = image;
            }
            else{
                rows[i][4] = null;
            }
                rows[i][5] = list.get(i).getBatre();
                rows[i][6] = list.get(i).getKamera();                
                rows[i][7] = list.get(i).getOs();
                rows[i][8] = list.get(i).getRam();                
        }
        
        TheModel model = new TheModel(rows, columnName);
        jTable1.setModel(model);
    }
        String s;
         PreBuy pb = new PreBuy();

    /**
     * Creates new form UserBrandInterface
     */
    public UserBrandInterface() throws SQLException {
        initComponents();
        populate();
        BindCombo();
    }

        public void BindCombo() throws SQLException{
                Connect con = new Connect();
                Connection myconObj = con.connect();
        
                Statement st = myconObj.createStatement();
                ResultSet rs = st.executeQuery("SELECT `Amount`,`PhoneName`,`Merek`, `Harga`,`Picture` FROM `data hp`");
                while(rs.next()){
                jComboBox1.addItem(rs.getString(2));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton7.setText("SIGN OUT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setText("BRAND");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(90);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
                            .addComponent(jButton7))
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                 this.setVisible(false);
                 LoginRegister logreg = new LoginRegister ();
                 logreg.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
          String pn = model.getValueAt(index, 1).toString();
          String merek = model.getValueAt(index, 2).toString();
          String harga = model.getValueAt(index, 3).toString();
          
          ImageIcon image3 = null;
          
     if(jTable1.getValueAt(index, 4) != null) {
        ImageIcon image1 = (ImageIcon)jTable1.getValueAt(index, 4);
        Image image2 = image1.getImage().getScaledInstance(pb.jLabel1.getWidth(), pb.jLabel1.getHeight()
                 , Image.SCALE_SMOOTH);
       image3 = new ImageIcon(image2);
     }else{
            System.out.println("No Image");
        }
     
          String batre = model.getValueAt(index, 5).toString();
          String cam = model.getValueAt(index, 6).toString();
          String os = model.getValueAt(index, 7).toString();
          String ram = model.getValueAt(index, 8).toString();

          pb.setVisible(true);
          pb.pack();
          pb.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);   
          //set all to be public
          pb.jLabel14.setText(pn);
          pb.jLabel13.setText(merek);
          pb.jLabel9.setText(harga);
          pb.jLabel1.setIcon(image3); 

          pb.jLabel12.setText(model.getValueAt(index, 5).toString());
                 
          pb.jLabel6.setText(cam);
          pb.jLabel11.setText(os);
          pb.jLabel10.setText(ram);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         try {
             UpdateTable mq = new UpdateTable();
             ArrayList<Product2> list = mq.getData((String) jComboBox1.getSelectedItem());
             String[] columnName = {"Amount","PhoneName","Merek","Harga", "Picture"};
             Object[][] rows = new Object[list.size()][9];
             for(int i = 0; i < list.size(); i++){
                 rows[i][0] = list.get(i).getAmount();
                 rows[i][1] = list.get(i).getBrand();
                 rows[i][2] = list.get(i).getMerek();
                 rows[i][3] = list.get(i).getHarga();
                 if(list.get(i).getImage() != null){
                     ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getImage()).getImage()
                             .getScaledInstance(80, 80, Image.SCALE_SMOOTH) );
                     rows[i][4] = image;
                 }
                 else{
                     rows[i][4] = null;
                 }
                 System.err.println(list.get(i) == null);
                 rows[i][5] = list.get(i).getBatre();
                 rows[i][6] = list.get(i).getKamera();
                 rows[i][7] = list.get(i).getOs();
                 rows[i][8] = list.get(i).getRam();
             }
             
             TheModel model = new TheModel(rows, columnName);
             jTable1.setModel(model);
         } catch (SQLException ex) {
             Logger.getLogger(UserBrandInterface.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserBrandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserBrandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserBrandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserBrandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserBrandInterface().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserBrandInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
